language: node_js
node_js:
- "lts/*"
env:
  global:
  - GH_REF: github.com/chad-autry/react-bp
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build
after_success:
- chmod ugo+x ./deploy-gh-pages.sh
- ./deploy-gh-pages.sh
