language: node_js
node_js:
- "lts/*"
env:
  global:
  - GH_REF: github.com/chad-autry/react-bp
services:
  - xvfb
script:
- npm run build
after_success:
- chmod ugo+x ./deploy-gh-pages.sh
- ./deploy-gh-pages.sh
